# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "finbarrbrady/streammaster:configHardcodeFix_29"
  #amd64: "finbarrbrady/streammaster:configHardcodeFix_11"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Streammaster add-on"
  org.opencontainers.image.description: "Streammaster add-on."
  org.opencontainers.image.source: "https://github.com/fbradyirl/streammaster-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
