# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: StreamMaster add-on
version: "1.0"
slug: streammaster
description: "Custom addon to run StreamMaster"
url: "https://github.com/fbradyirl/streammaster-addon/tree/main/streammaster"
ingres: true
ingress_port: 7095
host_network: true
arch:
  - aarch64
  - amd64
init: false
map:
  - type: homeassistant_config
    read_only: False
    path: /config
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/fbradyirl/{arch}-streammaster-addon"
