# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: StreamMaster add-on
version: "1.0.20"
slug: streammaster
description: "Custom addon to run StreamMaster"
url: "https://github.com/fbradyirl/streammaster-addon/tree/main/streammaster"
# ingress: true
# ingress_port: 7095
# ingress_stream: false
# ingress_entry: /editor/streams
# panel_icon: mdi:television-classic
# panel_title: StreamMaster
host_network: true
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addons
    read_only: false
  - type: all_addon_configs
    read_only: false
  - type: backup
    read_only: false
  - type: addon_config
    read_only: False
    path: /config
  - type: media
    read_only: false
  - type: share
    read_only: false
  - type: ssl
    read_only: false
options:
  set_perms: false
  db_dir: "/config/DB"
schema:
  set_perms: bool
  db_dir: str
image: "ghcr.io/fbradyirl/{arch}-streammaster-addon"
